import {
  ExceptionsSlide,
  LifecycleSlide,
  MarginSlide,
  ScaleSlide,
  TitleSlide,
  ValueAtStakeSlide,
} from "./Opening";
import {
  AgentAppViewSlide,
  LeadershipViewSlide,
  Phase1CloseSlide,
  Phase1ExistsSlide,
  Phase1FeaturesSlide,
} from "./Phase1";
import {
  CreditGraphSlide,
  CrmEngagementSlide,
  CustomerWebsiteSlide,
  DataAssetSlide,
  DocumentAISlide,
  GrowthOutreachSlide,
  LenderRoutingSlide,
  PartnerAnalyticsSlide,
  Phase2CloseSlide,
  PredictivePromptsSlide,
  ReconciliationSlide,
  StrategicPositionSlide,
} from "./Phase2";
import {
  ClosingSlide,
  ConsiderationsSlide,
  InvestmentSlide,
} from "./Close";

export const slides = [
  TitleSlide,
  ScaleSlide,
  MarginSlide,
  ValueAtStakeSlide,
  ExceptionsSlide,
  LifecycleSlide,
  Phase1ExistsSlide,
  LeadershipViewSlide,
  AgentAppViewSlide,
  Phase1FeaturesSlide,
  Phase1CloseSlide,
  DocumentAISlide,
  LenderRoutingSlide,
  ReconciliationSlide,
  PartnerAnalyticsSlide,
  PredictivePromptsSlide,
  DataAssetSlide,
  CreditGraphSlide,
  StrategicPositionSlide,
  CrmEngagementSlide,
  CustomerWebsiteSlide,
  GrowthOutreachSlide,
  Phase2CloseSlide,
  InvestmentSlide,
  ConsiderationsSlide,
  ClosingSlide,
];

export const slideLabels = [
  "Title",
  "Scale",
  "Margin",
  "Value at stake",
  "Exceptions",
  "Lifecycle",
  "Exists",
  "Leadership view",
  "Agent app",
  "Features",
  "Phase I close",
  "Document AI",
  "Lender routing",
  "Reconciliation",
  "Partner analytics",
  "Predictive prompts",
  "Data asset",
  "Credit Graph",
  "Strategic position",
  "CRM & WhatsApp",
  "Customer website",
  "Growth outreach",
  "Phase II close",
  "Scope & timeline",
  "Considerations",
  "Closing",
];
