import {
  ExceptionsSlide,
  LifecycleSlide,
  MarginSlide,
  ScaleSlide,
  TitleSlide,
  ValueAtStakeSlide,
} from "./Opening";
import {
  LeadershipViewSlide,
  Phase1CloseSlide,
  Phase1ExistsSlide,
  Phase1FeaturesSlide,
} from "./Phase1";
import {
  CreditGraphSlide,
  DataAssetSlide,
  DocumentAISlide,
  LenderRoutingSlide,
  PartnerAnalyticsSlide,
  Phase2CloseSlide,
  PredictivePromptsSlide,
  ReconciliationSlide,
  StrategicPositionSlide,
} from "./Phase2";
import {
  AlternativesSlide,
  ClosingSlide,
  ConsiderationsSlide,
  EvidenceSlide,
  InternalCaseSlide,
  InvestmentSlide,
  TwoPhasesSlide,
} from "./Close";

export const slides = [
  TitleSlide,
  ScaleSlide,
  MarginSlide,
  ValueAtStakeSlide,
  ExceptionsSlide,
  LifecycleSlide,
  Phase1ExistsSlide,
  LeadershipViewSlide,
  Phase1FeaturesSlide,
  Phase1CloseSlide,
  DocumentAISlide,
  LenderRoutingSlide,
  ReconciliationSlide,
  PartnerAnalyticsSlide,
  PredictivePromptsSlide,
  DataAssetSlide,
  CreditGraphSlide,
  StrategicPositionSlide,
  Phase2CloseSlide,
  TwoPhasesSlide,
  AlternativesSlide,
  EvidenceSlide,
  InvestmentSlide,
  ConsiderationsSlide,
  InternalCaseSlide,
  ClosingSlide,
];

export const slideLabels = [
  "Title",
  "Scale",
  "Margin",
  "Value at stake",
  "Exceptions",
  "Lifecycle",
  "Exists",
  "Leadership view",
  "Features",
  "Phase 1 close",
  "Document AI",
  "Lender routing",
  "Reconciliation",
  "Partner analytics",
  "Predictive prompts",
  "Data asset",
  "Credit Graph",
  "Strategic position",
  "Phase 2 close",
  "Two phases",
  "Alternatives",
  "Evidence",
  "Investment",
  "Considerations",
  "Internal case",
  "Closing",
];
